image: node:10-alpine

stages:
  - test
  - build

lint:
  stage: test
  script:
    - install_dependencies
    - npx pnpm run lint
  cache:
    paths:
      - node_modules

build:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - build
    - push_image
  except:
    - master

.devops: &devops |
  function install_dependencies () {
    npx pnpm install
  }

  function build () {
    docker build -t $(version) -t $(version latest) .
  }

  function version () {
    echo "$(docker_registry)/hermes:$(version_tag $1)"
  }

  function docker_registry () {
    echo "${REGISTRY_URI}"
    return 0
  }

  function version_prefix () {
    case "$CI_COMMIT_REF_NAME" in
      release)
        echo "rc"
        return 0
        ;;
      *)
        echo "alpha"
        return 0
        ;;
    esac
  }

  function version_tag () {
    if [[ -z "$CI_COMMIT_TAG" ]];
    then
      if [[ -z "$1" ]];
        then echo "$(version_prefix)-${CI_COMMIT_SHA:0:6}"
        else echo "$(version_prefix)-$1"
      fi
    else
      echo "$CI_COMMIT_TAG"
    fi
  }

  function push_image () {
    if [[ "$CI_COMMIT_REF_NAME" != "release" && "$CI_COMMIT_REF_NAME" != "release" && -z "$CI_COMMIT_TAG"]]; then
      return 0
    fi

    echo ${REGISTRY_PASSWORD} | docker login ${REGISTRY_URI} -u ${REGISTRY_USER} --password-stdin
    docker push "$(docker_registry)/hermes"
  }

before_script:
    - *devops
